# ===============================
# CONFIGURATION SERVEUR
# ===============================
server.port=8080

# ===============================
# CONFIGURATION POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_trello
spring.datasource.username=postgres
spring.datasource.password=nano
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# NOM DE L'APPLICATION
# ===============================
spring.application.name=mini-trello

# ===============================
# JWT CONFIGURATION
# ===============================
app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
app.jwt.expiration=86400000

spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=false

# Upload configuration
file.upload-dir=./uploads/taches/
file.upload-dir-images=./uploads/taches/images/
file.upload-dir-thumbnails=./uploads/taches/thumbnails/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true